exports.handler = async function(event, context) {
  if (event.httpMethod !== 'POST') {
    return {
      statusCode: 405,
      body: JSON.stringify({ error: 'Method not allowed' })
    };
  }

  const { token, action, boardId, data } = JSON.parse(event.body);

  if (!token) {
    return {
      statusCode: 401,
      body: JSON.stringify({ error: 'No token provided' })
    };
  }

  try {
    if (action === 'create_board') {
      const res = await fetch('https://api.miro.com/v2/boards', {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          name: "Don't Panic — My Canvas",
          description: 'Generated by the Don\'t Panic self-assessment tool.'
        })
      });

      const board = await res.json();

      if (!res.ok) {
        return {
          statusCode: res.status,
          body: JSON.stringify({ error: 'Failed to create board', details: board })
        };
      }

      return {
        statusCode: 200,
        body: JSON.stringify({ boardId: board.id, boardUrl: board.viewLink })
      };
    }

    if (action === 'write_card') {
      if (!boardId || !data) {
        return {
          statusCode: 400,
          body: JSON.stringify({ error: 'Missing boardId or data' })
        };
      }

      const res = await fetch(`https://api.miro.com/v2/boards/${boardId}/sticky_notes`, {
        method: 'POST',
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({
          data: { content: data.content || '' },
          position: { x: data.x || 0, y: data.y || 0 },
          geometry: { width: 400 }
        })
      });

      const card = await res.json();

      if (!res.ok) {
        return {
          statusCode: res.status,
          body: JSON.stringify({ error: 'Failed to write card', details: card })
        };
      }

      return {
        statusCode: 200,
        body: JSON.stringify({ cardId: card.id })
      };
    }

    return {
      statusCode: 400,
      body: JSON.stringify({ error: 'Unknown action' })
    };

  } catch (err) {
    return {
      statusCode: 500,
      body: JSON.stringify({ error: 'Server error', details: err.message })
    };
  }
};
